spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-netwok"


#pour maildev
#  mail:
#    host: localhost
#    port: 1025
#    username: ali
#    password: ali
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000

  mail:
    host: ${EMAIL_HOSTNAME:smtp.gmail.com} #smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:fahdzizou@gmail.com} #fahdzizou@gmail.com
    password: ${EMAIL_PASSWORD:wfmnxgkkkqqprsza} #wfmnxgkkkqqprsza   # ton App Password, sans espaces
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            enable: false
    protocol: smtp

application:
#  security:
#    jwt:
#      secret-key: 0d237769381ad3a4a381dc611c7f2cdf2b40350e999b7ffc1a3c3e5899752a26
#      expiration: 8640000
#
#  mailing:
#    frontend:
#      activation-url: http://localhost:4200/activate-account
#
#  cors:
#    origins: http://localhost:4200,http://localhost:8080

  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088
